version: '3.8'

services:
  mariadb:
    env_file:
      - .env
    image: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    init: true
    ports:
      - 3306:3306
    volumes:
      - ~/data/wpdb:/var/lib/mysql/wordpressdb
    restart: always
    networks:
      - blue_network

  nginx:
    env_file:
      - .env
    image: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
      args:
        - CERTS_=${CERTS_}
    init: true
    ports:
     # - 443:443
      - 9000:9000
    volumes:
      - ~/data/wpweb:/var/www/html/${DOMAIN_NAME}
    restart: always
    networks:
      - blue_network

  wordpress:
      env_file:
        - .env
      image: wordpress
      build:
        context: requirements/wordpress
        dockerfile: Dockerfile
        args:
          - DOMAIN_NAME=${DOMAIN_NAME}
      init: true
      restart: always
      volumes:
        - ~/data/wpweb:/var/www/html/${DOMAIN_NAME}

   #   ports: 
 #      - 3306:3306
  #     - 9000:9000
      networks:
        - blue_network  
    

networks:
  blue_network:

