version: '3.9'

services:
  mariadb:
    env_file:
      - .env
    image: mariadb
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    init: true
    ports:
      - 3306:3306
    volumes:
      - mariadb-volume:/var/lib/mysql
    restart: always
    networks:
      - blue_network
  nginx:
    env_file:
      - .env
    container_name: nginx
    image: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    init: true
 #   ports:
 #     - 443:443
 #     - 9000:9000
   # volumes:
    #  - ~/data/wpweb:/var/www/html/${DOMAIN_NAME}/wordpress
    restart: always
    networks:
      - blue_network

  wordpress:
      depends_on:
        - mariadb
      env_file:
        - .env
      container_name: wordpress
      image: wordpress
      build:
        context: requirements/wordpress
        dockerfile: Dockerfile
        args:
          - DOMAIN_NAME=${DOMAIN_NAME}
      init: true
      restart: always
    #  volumes:
    #    - ~/data/wpweb:/var/www/html/${DOMAIN_NAME}/wordpress
      networks:
        - blue_network  
    
networks:
  blue_network:

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/kat/data/mariadb
