version: '3.9'

services:
  mariadb:
    env_file:
      - .env
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    init: true
    volumes:
      - mariadb-volume:/var/lib/mysql
    restart: always
    networks:
      - blue-network
    #ports:
    #  - 3306:3306
  nginx:
    depends_on:
      - wordpress
    env_file:
      - .env
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    init: true
    volumes:
      - wordpress-volume:/var/www/html
    restart: always
    networks:
      - blue-network
    ports:
      - 80:80
  wordpress:
      depends_on:
        - mariadb
      env_file:
        - .env
      container_name: wordpress
      build:
        context: requirements/wordpress
        dockerfile: Dockerfile
        args:
          - DOMAIN_NAME=${DOMAIN_NAME}
      init: true
      restart: always
      volumes:
      - wordpress-volume:/var/www/html
      networks:
        - blue-network
    #  ports:
    #    - 9000:9000
networks:
  blue-network:
    name: blue-network
volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/data/mariadb
  wordpress-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/data/wordpress

