version: '3.8'
services:
  mariadb:
    image: mariadb
    user: "mysql:mysql"
    init: true
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
   # - type: bind
    #  source: ~/data/db
     # target: /var/lib/mysql/db
      - ~/data/db:/var/lib/mysql/db
    restart: always


