version: '3.8'
services:
  mariadb:
    env_file:
      - .env
    image: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    init: true
    ports:
      - 3306:3306
    volumes:
      - ~/data/wpdb:/var/lib/mysql/wordpressdb
    restart: always
    networks:
      - blue_network

  nginx:
    image: nginx
    build: requirements/nginx
    init: true
    ports:
     # - 443:443
      - 9000:9000
   # volumes:
  #    - ~/data/wpweb:/
    restart: always
    networks:
      - blue_network

  wordpress:
      image: wordpress
      build: requirements/wordpress
      init: true
      restart: always
   #   ports: 
 #      - 3306:3306
  #     - 9000:9000
      networks:
        - blue_network  
    

networks:
  blue_network:

