version: '3.9'

services:
  nginx:
    depends_on:
      - wordpress
    env_file:
      - .env
    container_name: nginx
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    init: true
    volumes:
      - wordpress-volume:/var/www/html
    restart: always
    networks:
      - blue-network
    ports:
      - 443:443
  mariadb:
    env_file:
      - .env
    container_name: mariadb
    build: requirements/mariadb
    init: true
    volumes:
      - mariadb-volume:/var/lib/mysql/
    restart: always
    networks:
      - blue-network
  wordpress:
      depends_on:
       - mariadb
      env_file:
       - .env
      container_name: wordpress
      build: requirements/wordpress
      init: true
      restart: always
      volumes:
      - wordpress-volume:/var/www/html
      networks:
       - blue-network

networks:
  blue-network:
    name: blue-network

volumes:
  mariadb-volume:
    name: mariadb-volume
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/data/mariadb
  wordpress-volume:
    name: wordpress-volume
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/data/wordpress