version: '3.9'

services:
  mariadb:
    env_file:
      - .env
    image: mariadb
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    init: true
    volumes:
      - mariadb-volume:/var/lib/mysql
    restart: always
    networks:
      - db
    ports:
      - 3306:3306
  nginx:
    depends_on:
      - wordpress
    env_file:
      - .env
    container_name: nginx
    image: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    init: true
    volumes:
      - wordpress-volume:/var/www/html
    restart: always
    networks:
      - web
    ports:
      - 80:80
  wordpress:
      depends_on:
        - mariadb
      env_file:
        - .env
      container_name: wordpress
      image: wordpress
      build:
        context: requirements/wordpress
        dockerfile: Dockerfile
        args:
          - DOMAIN_NAME=${DOMAIN_NAME}
      init: true
      restart: always
      volumes:
      - wordpress-volume:/var/www/html
      networks:
        - web 
        - db
      ports:
        - 9000:9000
networks:
  db:
  web:
volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/data/mariadb
  wordpress-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/data/wordpress

